name: Build APK

on:
  workflow_dispatch:
  push:
    branches:
      - '**/tv/**'
      - 'tv*'
      - 'feature/tv*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.44.8'

      - run: flutter pub get

      - run: flutter build apk --debug

      - uses: actions/upload-artifact@v4
        with:
          name: piliplus-debug-apk
          path: build/app/outputs/flutter-apk/*.apk
