name: Build (Fork)

on:
  workflow_dispatch:
    inputs:
      build_android:
        description: "Build Android"
        required: false
        default: true
        type: boolean
      build_win_x64:
        description: "Build Win-x64"
        required: false
        default: true
        type: boolean

jobs:
  android:
    if: ${{ inputs.build_android }}
    name: Build Android
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: "zulu"
          java-version: "17"
          cache: "gradle"
          cache-dependency-path: |
            android/*.gradle*
            android/**/gradle-wrapper.properties

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml
          cache: true

      - name: Apply Patch
        shell: pwsh
        run: lib/scripts/patch.ps1 android
        continue-on-error: true

      - name: Write signing key
        run: |
          if [ ! -z "${{ secrets.SIGN_KEYSTORE_BASE64 }}" ]; then
            echo "${{ secrets.SIGN_KEYSTORE_BASE64 }}" | base64 --decode > android/app/key.jks
            echo storeFile='key.jks' >> android/key.properties
            echo storePassword='${{ secrets.KEYSTORE_PASSWORD }}' >> android/key.properties
            echo keyAlias='${{ secrets.KEY_ALIAS }}' >> android/key.properties
            echo keyPassword='${{ secrets.KEY_PASSWORD }}' >> android/key.properties
          fi

      - name: Set and Extract version
        shell: pwsh
        run: lib/scripts/build.ps1 android

      - name: Build APK
        run: flutter build apk --release --split-per-abi --dart-define-from-file=pili_release.json --pub

      - name: Rename APKs
        shell: bash
        run: |
          for file in build/app/outputs/flutter-apk/app-*-release.apk; do
            abi=$(echo "$file" | sed -E 's|.*app-(.*)-release\.apk|\1|')
            mv "$file" "PiliPlus_android_${{ env.version }}_${abi}.apk"
          done

      - name: Upload Android artifacts
        uses: actions/upload-artifact@v7
        with:
          archive: false
          name: Android-release
          path: PiliPlus_android_*.apk

  win_x64:
    if: ${{ inputs.build_win_x64 }}
    uses: ./.github/workflows/win_x64.yml
    permissions:
      contents: read
